news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('featured/<str:slug>', views.featured_news_detail,
         name='featured_news_detail'),
    path('search', views.search, name='search'),
    path('community', views.community_news, name='community'),
    path('comment', views.add_comment, name='add_comment'),
    path('create', views.create_community_news, name='create'),
    path('community/<str:slug>', views.community_detail, name='community_detail'),
    path('community/search/', views.community_search, name='community_search')
]

reddit_news/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.views.generic.base import RedirectView

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', RedirectView.as_view(url='/news')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.fetch_user_details, name='user_profile'),
    path('profile/<str:username>', views.fetch_user_details, name='profile'),
    path('search_profiles', views.search_profiles, name='search_profiles'),
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register'),
    path('logout', views.logout_user, name='logout'),
    path('delete', views.delete_news, name='delete'),
    path('all_profiles', views.show_all_profiles, name='all'),
    path('upload', views.upload_avatar, name='upload_avatar')
]

news/models.py
# pylint: disable=no-member
# pylint: disable=missing-module-docstring


from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify


from django.utils.timezone import now
from django.urls import reverse

from PIL import Image


User = get_user_model()

# Create your models here.


# This will behave as cache for FeaturedNews
class FeaturedNews(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.CharField(
        max_length=255, blank=True, null=True, default='Anonymous')
    description = models.TextField()
    content = models.TextField()
    category = models.CharField(max_length=20)
    url = models.URLField(max_length=400)
    image_url = models.URLField(
        max_length=400, null=True, default='/static/images/register_background.jpg')
    published_date = models.DateTimeField(default=now)

    class Meta:
        indexes = [
            models.Index(fields=['slug'])
        ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if self.author is None:
            self.author = 'Anonymous'
        if self.image_url is None:
            self.image_url = '/static/images/register_background.jpg'
        super(FeaturedNews, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse("news:featured_news_detail", kwargs={"slug": self.slug})


class Timestamp(models.Model):
    creationDate = models.DateTimeField(default=now)

    def __str__(self) -> str:
        return f'{self.creationDate}'


class CommunityNews(models.Model):

    CATEGORIES = (
        ("business", "Business"),
        ("entertainment", "Entertainment"),
        ("sports", "Sports"),
        ("lifestyle", "Lifestyle"),
        ("technology", "Technology"),
        ("others", "Others")
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='news')
    banner = models.ImageField(
        default='default_news.jpg', upload_to='community_news')
    description = models.TextField(max_length=400)
    content = models.TextField()
    published_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.CharField(
        max_length=20, choices=CATEGORIES, default="lifestyle")

    def get_total_upvotes(self):
        return self.upvotes.users.count()

    def get_total_downvotes(self):
        return self.downvotes.users.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        super(CommunityNews, self).save(*args, **kwargs)

        banner_image = Image.open(self.banner.path)

        if banner_image.height > 600 or banner_image.width > 800:
            output_size = (600, 800)
            banner_image.thumbnail(output_size)

            banner_image.save(self.banner.path)

    def __str__(self) -> str:
        return f'{self.title}'


class Comment(models.Model):
    description = models.CharField(max_length=150, null=False, blank=False)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    news = models.ForeignKey(
        CommunityNews, on_delete=models.CASCADE, related_name='comments')
    published_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.description}'


class UpVote(models.Model):
    news = models.OneToOneField(
        CommunityNews, related_name='upvotes', on_delete=models.CASCADE)
    users = models.ManyToManyField(
        User, related_name='requirement_news_upvotes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.news.title}'


class DownVote(models.Model):
    news = models.OneToOneField(
        CommunityNews, related_name='downvotes', on_delete=models.CASCADE)
    users = models.ManyToManyField(
        User, related_name='requirement_news_downvotes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.news.title}'

news/forms.py
from django import forms
from .models import CommunityNews

class CommunityNewsCreateForm(forms.ModelForm):
    class Meta:
        model = CommunityNews
        fields = ['banner', 'title', 'category', 'description', 'content']

news/views.py
# pylint: disable=missing-module-docstring
# pylint: disable=no-member

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.conf import settings
from newsapi import NewsApiClient
import json
import requests

from bs4 import BeautifulSoup

from django.utils import timezone
from django.utils.dateparse import parse_datetime
from django.template.defaultfilters import slugify

from django.contrib.auth.decorators import login_required

from .models import FeaturedNews, Timestamp, CommunityNews, Comment
from .forms import CommunityNewsCreateForm

import logging

logger = logging.getLogger("herokulogger")


def fetch_country_code():
    # getting the geolocation response

    # keeping this external api call in a try-catch block in order to make sure application
    # runs smoothly

    try:
        geolocation_response = requests.get(
            settings.GEOLOCATION_API_URL, verify=False, timeout=10)

        logger.info("Geolocation response: %s", str(geolocation_response))

        if geolocation_response is not None and geolocation_response.content is not None:
            data = json.loads(geolocation_response.content)
            return data.get('country_code')

    except Exception as exception:
        logger.error("exception happened during GEOLOCATION API call: %s", repr(exception))

    return None


def add_to_database_from_api(news_api_client, category, country_code):
    news_api_client = NewsApiClient(api_key=settings.NEWSAPI_KEY)

    # try:

    if category == 'headlines':

        top_news_response = news_api_client.get_top_headlines(
            language='en', country='us')

    else:
        top_news_response = news_api_client.get_top_headlines(
            language='en', category=category, country=country_code.lower()
        )
    # max news
    MAX_NEWS_EACH_CATEGORY = 6

    # first of all getting the top_news_response
    if top_news_response is not None and top_news_response.get('articles') is not None:
        current_total = 0
        for top_news in top_news_response.get('articles'):
            if current_total >= MAX_NEWS_EACH_CATEGORY:
                break
            if top_news.get('title') is not None and \
                    top_news.get('description') is not None and \
                    top_news.get('content') is not None:
                try:
                    if not FeaturedNews.objects.filter(slug=slugify(top_news.get('title'))):
                        current_news = FeaturedNews(title=top_news.get('title'),
                                                    author=top_news.get(
                                                        'author', 'anonymous'),
                                                    description=top_news.get(
                            'description'),
                            content=top_news.get(
                            'content'),
                            category=category,
                            url=top_news.get('url'),
                            image_url=top_news.get(
                            'urlToImage'),
                            published_date=parse_datetime(
                            top_news.get('publishedAt'))
                        )

                        current_news.save()
                        current_total += 1
                    else:
                        continue
                except Exception as exception:
                    logger.error("Exception happened: %s", repr(exception))

    # except Exception as exception:
    #     logger.error("Exception %s", repr(exception))
    #     traceback.print_exc()

# Create your views here.
def populate_featured_news_database():
    # check the timestamp table first
    # if there is no timestamp or the current timestamp value is 1 hour before
    # then do the db populating
    will_populate_db = False
    if not Timestamp.objects.all().exists():
        current_timestamp = Timestamp()
        current_timestamp.save()
        will_populate_db = True

    present_timestamp = timezone.now()
    current_timestamp_object = Timestamp.objects.all()[0]
    stored_timestamp = current_timestamp_object.creationDate

    elapsed_time_in_hours = (
        present_timestamp - stored_timestamp).seconds / 3600

    if elapsed_time_in_hours >= 2:
        # more than an hour has passed so we need to add updated news to the collection
        will_populate_db = True

        # update the timestamp
        current_timestamp_object.creationDate = present_timestamp
        current_timestamp_object.save()

    if will_populate_db:
        # populate the db
        country_code = fetch_country_code()

        if country_code is None:
            country_code = 'us'

        news_api_client = NewsApiClient(api_key=settings.NEWSAPI_KEY)

        logger.info("Country code fetched: %s", country_code)

        # first of all delete all the records from the table
        FeaturedNews.objects.all().delete()

        logger.info("Populating headlines")
        print("Populating headlines")

        add_to_database_from_api(news_api_client, "headlines", country_code)


        logger.info("Populating business news")

        add_to_database_from_api(news_api_client, "business", country_code)

        logger.info("Populating technology news")

        add_to_database_from_api(news_api_client, "technology", country_code)

        logger.info("Populating sports news")

        add_to_database_from_api(news_api_client, "sports", country_code)


def index(request):

    populate_featured_news_database()

    featured_news = FeaturedNews.objects.filter(
        category="headlines").order_by("-published_date")[:6]
    business_news = FeaturedNews.objects.filter(
        category="business").order_by("-published_date")[:6]
    tech_news = FeaturedNews.objects.filter(
        category="technology").order_by("-published_date")[:6]
    sports_news = FeaturedNews.objects.filter(
        category="sports").order_by("-published_date")[:6]

    context = {
        'featured': featured_news,
        'business': business_news,
        'technology': tech_news,
        'sports': sports_news
    }

    return render(request, 'news/index.html', context=context)


@login_required(login_url='/users/login')
def featured_news_detail(request, slug):
    news = get_object_or_404(FeaturedNews, slug=slug)

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'}

    r = requests.get(news.url, headers=headers, timeout=5)
    soup = BeautifulSoup(r.content, "html.parser")


    content = []
    for paragraph in soup.find_all('p'):
        paragraph_text = paragraph.get_text()
        if len(paragraph_text) > 0:
            content.append(f'<p>{paragraph.get_text()}</p>')

    # use beautiful soup to extract the url

    if len(content) == 0:
        try:
            text = news.content[:news.content.index('[+')]
        except ValueError:
            text = news.content
    else:
        text = ''.join(content)

    context = {
        'news': news,
        'text': text
    }
    return render(request, 'news/featured_news_detail.html', context=context)


def search(request):
    # here will be calling the search api
    search_term = request.GET.get('search')
    if search_term is None or search_term.strip() == '':
        return redirect(reverse('news:index'))

    # call the news api and fetch the data

    search_results = []

    news_api_client = NewsApiClient(api_key=settings.NEWSAPI_KEY)

    articles = news_api_client.get_everything(
        q=search_term, sort_by='relevancy', page=1, language='en')

    if articles is not None and articles.get('articles') is not None:
        print(len(articles.get('articles')))
        for article in articles.get('articles')[:50]:
            if article.get('title') is not None and article.get('description') is not None and article.get('urlToImage') is not None and article.get('publishedAt') is not None:
                search_results.append({
                    'title': article.get('title'),
                    'description': article.get('description'),
                    'author': article.get('author', 'anonymous'),
                    'image_url': article.get('urlToImage'),
                    'url': article.get('url'),
                    'published_date': parse_datetime(article.get('publishedAt'))
                })

    print(search_results)

    context = {'term': search_term, 'search_results': search_results,
               'count': len(search_results)}
    return render(request, 'news/search_results.html', context=context)


def community_news(request):

    if request.GET.get('filter') is not None:
        selected_choice = request.GET.get('filter')
        news = CommunityNews.objects.filter(
            category=selected_choice).order_by('-published_at')[:50]
        title = f'Top {selected_choice.capitalize()} News'
    else:
        selected_choice = 'all'
        news = CommunityNews.objects.all().order_by('-published_at')[:50]
        title = 'Latest News'

    categories = ['all', 'technology', 'lifestyle',
                  'entertainment', 'sports', 'business', 'other']

    # trying to get the featured post
    # featured post is basically the post which is the post that has been for the current day

    context = {}

    try:
        latest_news = CommunityNews.objects.filter(published_at__gte=timezone.now(
        ).replace(hour=0, minute=0, second=0)).order_by('-published_at')
        most_liked_news_list = sorted(
            latest_news, key=lambda news: news.get_total_upvotes(), reverse=True)
        if len(most_liked_news_list) > 0:
            most_liked_news = most_liked_news_list[0]
            context['liked_news'] = most_liked_news
    except CommunityNews.upvotes.RelatedObjectDoesNotExist:
        pass

    context['categories'] = categories
    context['selected_choice'] = selected_choice

news/templates/news/community_news_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{news.title}}</title>
    <link rel="stylesheet" href="{% static 'news/css/community_detail.css' %}">
</head>

<body>
    <nav class="navbar">
        <div class="navbar_container">
            <div class="navbar_left">
                <div>
                    <a href="{% url 'news:index' %}"><img class="navbar_logo_img"
                            src="{% static 'images/logo_header_black.svg' %}" alt=""></a>
                </div>
            </div>
            <div class="navbar_right">
                <form method="get" action="{% url 'news:community_search' %}">
                    {% csrf_token %}
                    <div class="search_container">

                        <svg width="32" height="32" class="DFW_E nT46U VETef" viewBox="0 0 24 24" version="1.1"
                            aria-hidden="false">
                            <desc lang="en-US">A magnifying glass</desc>
                            <path
                                d="M16.5 15c.9-1.2 1.5-2.8 1.5-4.5C18 6.4 14.6 3 10.5 3S3 6.4 3 10.5 6.4 18 10.5 18c1.7 0 3.2-.5 4.5-1.5l4.6 4.5 1.4-1.5-4.5-4.5zm-6 1c-3 0-5.5-2.5-5.5-5.5S7.5 5 10.5 5 16 7.5 16 10.5 13.5 16 10.5 16z">
                            </path>
                        </svg>

                        <input class="search" type="search" name="search" placeholder="search community news">
                    </div>
                </form>
            </div>
            <div class="navbar_right__cta">
                <a style="font-size: 0.9rem;" href="{% url 'news:index' %}">Home</a>
                <a class="create_news_btn" href="{% url 'news:create' %}">Create News</a>
                {% if request.user.is_authenticated %}
                <div class="profile_img_container">
                    <button id="profile_btn" role="button" tabindex="0" aria-haspopup="true" aria-expanded="true"
                        type="button" class="profile_img_btn">
                        <div class="profile_img_btn__cta1">
                            <div class="profile_img_btn__cta2">
                                <img class="profile_img" loading="lazy" role="presentation"
                                    src="{{request.user.profile.image.url}}" alt="user profile image">
                            </div>
                        </div>
                    </button>
                </div>
                <div id="logout_menu" role="menu" tabindex="-1" style="display: none;">
                    <div class="menu-popup">
                        <div class="menu-popup__popover">
                            <div class="top_arrow">
                                <div class="top_arrow__cta1"></div>
                                <div classs="top_arrow__cta2"></div>
                            </div>
                            <div class="popup_content">
                                <ul class="menu_content">
                                    <li class="menu_item">
                                        <a role="link" tabindex="-1" aria-disabled="false" class="logout__cta"
                                            href="{% url 'users:user_profile' %}">Profile</a>
                                    </li>
                                    <li class="menu_item">
                                        <a role="link" tabindex="-1" aria-disabled="false" class="logout__cta"
                                            href="{% url 'users:logout' %}">Logout @{{request.user.username}}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <button class="login_btn"><a href="{% url 'users:login' %}">Log in</a></button>
                {% endif %}
            </div>
        </div>
        <ul class="categories_section">
            <li><a href="{% url 'news:index' %}">Featured</a></li>
            <li class="active"><a href="{% url 'news:community' %}">Community</a></li>
            <li><a href="{% url 'users:all' %}">Profiles</a></li>
        </ul>
    </nav>
    <main class="container">
        <section class="breadcrumb">
            <small>
                <a href="{% url 'news:community' %}">home</a> <span> > </span> <a
                    href="{% url 'news:community_detail' slug=news.slug %}" class="active_breadcrumb">{{news.slug}}</a>
            </small>
        </section>
        <section class="meta-section">

        </section>
        <section class="heading">
            <h1>{{news.title}}</h1>
        </section>
        <section class="image">
            <img src="{{news.banner.url}}" alt="{{news.title}}">
        </section>
        <section class="meta">
            By <a href="{% url 'users:profile' username=news.author.username %}">{{news.author}}</a> on {{news.published_at|date:"M d, Y"}} {{news.published_at|time:"H:i"}}
        </section>
        <section id="content">
            <ul class="categories_section shadow_low">
                <li id="editorial_controller" class="active">
                    <div>Editorial</div>
                </li>
                <li id="comments_section_controller">
                    <div>Comments</div>
                </li>
            </ul>
            <div class="content_section">
                <div id="editorial_section" class="content_item">
                    <p>
                        {{news.content | linebreaksbr | safe}}
                    </p>
                </div>
                <div id="comments_section" class="comment_section hidden">
                    <div class="add_comment">
                        {% if request.user.is_authenticated %}
                        <!-- create a form to add the comment -->
                        <form class="comment_form" action="{% url 'news:add_comment' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{news.slug}}" name="post_slug">
                            <div class="comment_row">
                                <div class="current_user_image">
                                    <img src="{{request.user.profile.image.url}}"
                                        alt="{{request.user.username}} profile image">
                                </div>
                                <div class="input_row">
                                    <textarea
                                        onkeyup="this.style.height='auto';this.style.height=(this.scrollHeight)+'px'"
                                        class="search" type="text" name="comment" placeholder="Add a comment"
                                        required></textarea>

                                </div>
                            </div>
                            <div class="comment_submit">
                                <button class="read_more" type="submit">Add Comment</button>
                            </div>
                        </form>
                        {% else %}
                        <!-- display message that you are not logged in -->
                        <div class="no_comment_allowed">
                            Please log in to comment on this news
                        </div>
                        {% endif %}
                    </div>
                    {% if comments %}
                    <div class="comment_section_1">
                        {% for comment in comments %}
                        <div class="comment_container">
                            <div class="comment_user_image">
                                <img src="{{comment.author.profile.image.url}}" alt="{{comment.author.username}}">
                            </div>
                            <div class="comment_user_body">
                                <div class="comment_user_meta">
                                    <strong>{{comment.author.username}}</strong>
                                    <small><span></span>{{comment.published_at|date:"M d, Y"}}
                                        {{comment.published_at|time:"H:i"}}</small>
                                </div>
                                <div class="comment_description">
                                    {{ comment.description }}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    {% else %}
                    <div class="no_comment_left">
                        No comments yet! Show your love by adding a &hearts; comment!
                    </div>
                    {% endif %}
                </div>
            </div>
        </section>
    </main>



    <script src="{% static 'news/js/navbar.js' %}" defer></script>

    <script>
        let isCommentSection = false;
        const editorialController = document.getElementById('editorial_controller');
        const commentsSectionController = document.getElementById('comments_section_controller');

        editorialController.addEventListener('click', (e) => {
            e.preventDefault();
            if (isCommentSection) {
                isCommentSection = !isCommentSection;
                document.getElementById('comments_section').classList.add('hidden');
                document.getElementById('editorial_section').classList.remove('hidden');
                editorialController.classList.add('active');
                commentsSectionController.classList.remove('active');

            }
        });

        commentsSectionController.addEventListener('click', (e) => {
            e.preventDefault();
            if (!isCommentSection) {
                isCommentSection = !isCommentSection;
                document.getElementById('comments_section').classList.remove('hidden');
                document.getElementById('editorial_section').classList.add('hidden');
                editorialController.classList.remove('active');
                commentsSectionController.classList.add('active');

            }
        })
    </script>

</body>

</html>

news/templates/news/news_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create News</title>
    <link rel="stylesheet" href="{% static 'news/css/news_create.css' %}">
</head>



<body>
    <div class="background">
        <div class="bg_svg1">
            <img src="{% static 'images/bg1.svg' %}" alt="">
        </div>
    </div>
    <main class="container">
        <section class="breadcrumb">
            <small>
                <a href="{% url 'news:community' %}">home</a> <span> > </span> <a href="#" class="active_breadcrumb">Create</a>
            </small>
        </section>
        <div class="heading">
            <h1>Create a community news!</h1>
        </div>
        <div class="form_messages">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <form class="post_create_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="read_more">Create News</button>
        </form>
    </main>


    <script src="{% static 'news/js/navbar.js' %}" defer></script>
</body>

</html>