news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('featured/<str:slug>', views.featured_news_detail,
         name='featured_news_detail'),
    path('search', views.search, name='search'),
    path('community', views.community_news, name='community'),
    path('comment', views.add_comment, name='add_comment'),
    path('create', views.create_community_news, name='create'),
    path('community/<str:slug>', views.community_detail, name='community_detail'),
    path('community/search/', views.community_search, name='community_search')
]

reddit_news/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.views.generic.base import RedirectView

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', RedirectView.as_view(url='/news')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.fetch_user_details, name='user_profile'),
    path('profile/<str:username>', views.fetch_user_details, name='profile'),
    path('search_profiles', views.search_profiles, name='search_profiles'),
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register'),
    path('logout', views.logout_user, name='logout'),
    path('delete', views.delete_news, name='delete'),
    path('all_profiles', views.show_all_profiles, name='all'),
    path('upload', views.upload_avatar, name='upload_avatar')
]

users/models.py
# pylint: disable=no-member

from django.db import models
from django.contrib.auth import get_user_model

from PIL import Image

# Create your models here.

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            # convert to rgb
            rgb_image = img.convert('RGB')
            rgb_image.save(self.image.path)


    def __str__(self) -> str:
        return f'{self.user.username} Profile'

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.db.models import Count

from news.models import CommunityNews

from . import constants


def index(request):
    return redirect(reverse('users:user_profile'))


@login_required(login_url='/users/login')
def fetch_user_details(request, username=None):

    user_model = get_user_model()

    current = False

    if username is None or username == request.user.username:
        # fetch the current profile
        user = request.user
        current = True
    else:
        user = get_object_or_404(user_model, username=username)

    news = user.news.order_by("-published_at")

    context = {'current': current, 'user': user, 'profile_news': news}
    return render(request, 'users/profile.html', context=context)


def login_user(request):
    if request.method == constants.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_model = get_user_model()

        if not user_model.objects.filter(username=username).exists():
            messages.error(request, 'Invalid Username')
            return redirect(reverse('users:login'))

        user = authenticate(username=username, password=password)

        if user is None:
            messages.error(request, 'Invalid Password')
            return redirect(reverse('users:login'))
        else:
            login(request, user)
            return redirect(request.GET.get('next', reverse('news:index')))

    elif request.method == constants.GET:
        if not request.user.is_authenticated:
            return render(request, 'users/login.html')

        return redirect(request.GET.get('next', reverse('news:index')))
    return None


def register_user(request):
    if request.method == constants.POST:
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        user_model = get_user_model()

        existing_user_by_username = user_model.objects.filter(
            username=username)

        if existing_user_by_username.exists():
            messages.error(request, 'Username already taken')
            return redirect(reverse('users:register'))

        # checking user by email
        existing_user_by_email = user_model.objects.filter(email=email)

        if existing_user_by_email.exists():
            messages.error(request, 'Email already exists. Try to login')
            return redirect(reverse('users:register'))

        # now try to save the user
        user = user_model.objects.create(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email
        )

        # setting the password
        user.set_password(password)

        user.save()

        messages.success(request, 'User created successfully! Login now')
        return redirect(reverse('users:login'))

    elif request.method == constants.GET:
        if not request.user.is_authenticated:
            return render(request, 'users/register.html')

        return redirect(reverse('news:index'))
    return None


@login_required(login_url="/users/login")
def delete_news(request):
    if request.method == 'POST':
        slug = request.POST.get('news_slug')
        if slug is not None and slug != '':
            news_to_delete = CommunityNews.objects.get(slug=slug)
            print(news_to_delete)

            # deleting the news
            news_to_delete.delete()

            return redirect(reverse('users:user_profile'))

    return redirect(reverse('news:community'))


def show_all_profiles(request):
    user_model = get_user_model()

    all_users = user_model.objects.alias(
        news_count=Count('news')).order_by('-news_count')

    total_users = all_users.count()

    context = {
        'users': all_users,
        'total_results': total_users
    }

    return render(request, 'users/all_users.html', context=context)


def search_profiles(request):
    if request.method == 'GET':
        if request.GET.get('search') is not None and request.GET.get('search') != '':
            search_term = request.GET.get('search')

            user_model = get_user_model()

            searched_users = user_model.objects.filter(
                username__icontains=search_term)

            found_users = searched_users.count()

            context = {
                'users': searched_users,
                'total_results': found_users,
                'term': search_term
            }

            return render(request, 'users/search_profiles.html', context=context)

    return redirect(reverse('users:all'))


def logout_user(request):
    logout(request)
    return redirect(reverse('news:index'))


@login_required(login_url='/users/login')
def upload_avatar(request):
    if request.method == 'POST' and request.user is not None:

        current_profile = request.user.profile
        current_profile.image = request.FILES.get('avatar')
        current_profile.save()

    return redirect(reverse('users:user_profile'))

users/templates/users/all_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rednews | Profiles</title>
    <link rel="stylesheet" href="{% static 'users/css/all.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar_container">
            <div class="navbar_left">
                <div>
                    <a href="{% url 'news:index' %}"><img class="navbar_logo_img"
                            src="{% static 'images/logo_header_black.svg' %}" alt=""></a>
                </div>
            </div>
            <div class="navbar_right">
                <form method="get" action="{% url 'users:search_profiles' %}">
                    <div class="search_container">

                        <svg width="32" height="32" class="DFW_E nT46U VETef" viewBox="0 0 24 24" version="1.1"
                            aria-hidden="false">
                            <desc lang="en-US">A magnifying glass</desc>
                            <path
                                d="M16.5 15c.9-1.2 1.5-2.8 1.5-4.5C18 6.4 14.6 3 10.5 3S3 6.4 3 10.5 6.4 18 10.5 18c1.7 0 3.2-.5 4.5-1.5l4.6 4.5 1.4-1.5-4.5-4.5zm-6 1c-3 0-5.5-2.5-5.5-5.5S7.5 5 10.5 5 16 7.5 16 10.5 13.5 16 10.5 16z">
                            </path>
                        </svg>

                        <input class="search" type="search" name="search" placeholder="search profiles">
                    </div>
                </form>
            </div>
            <div class="navbar_right__cta">
                <a style="font-size: 0.9rem;" href="{% url 'news:index' %}">Home</a>
                <a class="create_news_btn" href="{% url 'news:create' %}">Create News</a>
                {% if request.user.is_authenticated %}
                <div class="profile_img_container">
                    <button id="profile_btn" role="button" tabindex="0" aria-haspopup="true" aria-expanded="true"
                        type="button" class="profile_img_btn">
                        <div class="profile_img_btn__cta1">
                            <div class="profile_img_btn__cta2">
                                <img class="profile_img" loading="lazy" role="presentation"
                                    src="{{request.user.profile.image.url}}" alt="user profile image">
                            </div>
                        </div>
                    </button>
                </div>
                <div id="logout_menu" role="menu" tabindex="-1" style="display: none;">
                    <div class="menu-popup">
                        <div class="menu-popup__popover">
                            <div class="top_arrow">
                                <div class="top_arrow__cta1"></div>
                                <div classs="top_arrow__cta2"></div>
                            </div>
                            <div class="popup_content">
                                <ul class="menu_content">
                                    <li class="menu_item">
                                        <a role="link" tabindex="-1" aria-disabled="false" class="logout__cta"
                                            href="{% url 'users:logout' %}">Logout @{{request.user.username}}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <button class="login_btn"><a href="{% url 'users:login' %}">Log in</a></button>
                {% endif %}
            </div>
        </div>
        <ul class="categories_section">
            <li><a href="{% url 'news:index' %}">Featured</a></li>
            <li><a href="{% url 'news:community' %}">Community</a></li>
            <li class="active"><a href="{% url 'users:all' %}">Profiles</a></li>
        </ul>
    </nav>

    <main class="container">
        <div class="breadcrumb">
            <small>
                <a href="{% url 'news:index' %}">Home</a>
                <span> > </span>
                <span><a href="{% url 'users:all' %}">Profiles</a></span>
            </small>
        </div>
        <div class="profiles_section">
            <div class="section_header">
                <h1>All Community Members</h1>
            </div>
            <div class="profile_body">
                {% for user in users %}
                    <div class="profile_card">
                        <div class="profile_image">
                            <img src="{{user.profile.image.url}}" alt="{{user.username}} profile">
                        </div>
                        <div class="profile_content">
                            <div class="username_section">
                                @{{user.username}}
                            </div>
                            <small class="fullname_section">
                                {{user.first_name}} {{user.last_name}}
                            </small>
                            <div class="total_news">
                                <span>{{user.news.count}}</span> news posted
                            </div>
                        </div>
                        {% if request.user.is_authenticated %}
                        <div class="goto_profile">
                            <a class="read_more" style="color: #fff;" href="{% url 'users:profile' username=user.username  %}">See Profile</a>
                        </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>

    <script src="{% static 'news/js/navbar.js'%}" defer></script>
    <script>

    </script>
</body>
</html>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>This will contain the profile of the current user</p>
</body>
</html>

users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile | {{user.username}}</title>
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
</head>
<body>

    <nav class="navbar">
        <div class="navbar_container">
            <div class="navbar_left">
                <div>
                    <a href="{% url 'news:index' %}"><img class="navbar_logo_img"
                            src="{% static 'images/logo_header_black.svg' %}" alt=""></a>
                </div>
            </div>
            <div class="navbar_right">
                <form method="get" action="{% url 'users:search_profiles' %}">
                    <div class="search_container">

                        <svg width="32" height="32" class="DFW_E nT46U VETef" viewBox="0 0 24 24" version="1.1"
                            aria-hidden="false">
                            <desc lang="en-US">A magnifying glass</desc>
                            <path
                                d="M16.5 15c.9-1.2 1.5-2.8 1.5-4.5C18 6.4 14.6 3 10.5 3S3 6.4 3 10.5 6.4 18 10.5 18c1.7 0 3.2-.5 4.5-1.5l4.6 4.5 1.4-1.5-4.5-4.5zm-6 1c-3 0-5.5-2.5-5.5-5.5S7.5 5 10.5 5 16 7.5 16 10.5 13.5 16 10.5 16z">
                            </path>
                        </svg>

                        <input class="search" type="search" name="search" placeholder="search profiles">
                    </div>
                </form>
            </div>
            <div class="navbar_right__cta">
                <a style="font-size: 0.9rem;" href="{% url 'news:index' %}">Home</a>
                <a class="create_news_btn" href="{% url 'news:create' %}">Create News</a>
                {% if request.user.is_authenticated %}
                <div class="profile_img_container">
                    <button id="profile_btn" role="button" tabindex="0" aria-haspopup="true" aria-expanded="true"
                        type="button" class="profile_img_btn">
                        <div class="profile_img_btn__cta1">
                            <div class="profile_img_btn__cta2">
                                <img class="profile_img" loading="lazy" role="presentation"
                                    src="{{request.user.profile.image.url}}" alt="user profile image">
                            </div>
                        </div>
                    </button>
                </div>
                <div id="logout_menu" role="menu" tabindex="-1" style="display: none;">
                    <div class="menu-popup">
                        <div class="menu-popup__popover">
                            <div class="top_arrow">
                                <div class="top_arrow__cta1"></div>
                                <div classs="top_arrow__cta2"></div>
                            </div>
                            <div class="popup_content">
                                <ul class="menu_content">
                                    <li class="menu_item">
                                        <a role="link" tabindex="-1" aria-disabled="false" class="logout__cta"
                                            href="{% url 'users:logout' %}">Logout @{{request.user.username}}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <button class="login_btn"><a href="{% url 'users:login' %}">Log in</a></button>
                {% endif %}
            </div>
        </div>
        <ul class="categories_section">
            <li><a href="{% url 'news:index' %}">Featured</a></li>
            <li><a href="{% url 'news:community' %}">Community</a></li>
            {% if request.user.is_authenticated %}
                <li class="active"><a href="{% url 'users:user_profile' %}">Profile</a></li>
            {% endif %}

        </ul>
    </nav>

    <main class="container">
        <div class="breadcrumb">
            <small>
                <a href="{% url 'news:index' %}">Home</a>
                <span> > </span>
                <span><a href="{% url 'users:all' %}">Profiles</a></span>
                <span> > </span>
                <span><a href="{% url 'users:profile' username=user.username %}">{{user.username}}</a></span>
            </small>
        </div>
        <div class="profile_section">
            <div class="profile_left">
                <div class="profile_image" style="background-image: url('{{user.profile.image.url}}')">
                    <!-- <img src="{{user.profile.image.url}}" alt="{{user.username}} profile"> -->
                </div>
                {% if current %}
                    <div class="profile_image_change_section">
                        <form id="upload_avatar" class="upload_image_form" action="{% url 'users:upload_avatar' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <label class="image_upload_btn" for="upload_image">
                                <input type="file" name="avatar" id="upload_image" />
                                Upload new image
                            </label>
                        </form>
                    </div>
                {% endif %}
            </div>
            <div class="profile_right">
                <h1>@{{user.username}}</h1>
                <div class="full_name">
                    {{user.first_name}} {{user.last_name}}
                </div>
                <div class="member">
                    Member since <span>{{user.date_joined|date:"M d, Y"}}</span>
                </div>
            </div>
        </div>
        <hr>
        <div>
            {% if profile_news %}
            <section class="search_results">
                <div class="section_header">
                    <h1>News posted by {{user.username}}</h1>
                </div>
                <div class="section_content">
                    {% for news in profile_news %}
                        <div class="card">
                            <div class="card-img">
                                <img src="{{news.banner.url}}" alt="{{news.title}}" loading="lazy">
                            </div>
                            <div class="card-body">
                                <div class="card-title">
                                    <h1>{{news.title | safe}}</h1>
                                </div>
                                <div class="card-meta">
                                    {{news.published_at|date:"M d, Y"}} {{news.published_at|time:"H:i"}}
                                </div>
                                <div class="card-description">
                                    {{news.description | safe}}
                                </div>
                                <div class="card_footer">
                                    <hr class="hr">
                                    <div class="card-links">
                                        <button class="read_more">
                                            <a class="read_more_cta" href="{% url 'news:community_detail' slug=news.slug %}">
                                            Go to Source</a>
                                        </button>
                                        {% if current %}
                                            <button class="read_more">
                                                <a class="read_more_cta" target="_blank" href="{% url 'news:community_detail' slug=news.slug %}">
                                                Edit</a>
                                            </button>
                                            <form action="{% url 'users:delete' %}" style="display: inline-block;" method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="news_slug" value="{{news.slug}}">
                                                <button type="submit" class="read_more" style="background-color: #683A51; color: #fff; cursor: pointer;">
                                                    Delete
                                                </button>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            </section>

            {% else %}
                <div class="not_found_container">
                    <div class="image">
                        <img src="{% static 'images/not_found.svg' %}" alt="">
                    </div>
                    <div class="not_found__content">
                        Sorry! No news could be found!
                    </div>
                </div>
            {% endif %}
        </div>
    </main>

    <script src="{% static 'news/js/navbar.js'%}" defer></script>
    <script>
        document.getElementById('upload_image').addEventListener('change', (e) => {
            document.getElementById('upload_avatar').submit();
        })
    </script>
</body>
</html>

users/templates/users/search_profiles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results | {{term}}</title>
    <link rel="stylesheet" href="{% static 'users/css/all.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar_container">
            <div class="navbar_left">
                <div>
                    <a href="{% url 'news:index' %}"><img class="navbar_logo_img"
                            src="{% static 'images/logo_header_black.svg' %}" alt=""></a>
                </div>
            </div>
            <div class="navbar_right">
                <form method="get" action="{% url 'users:search_profiles' %}">
                    <div class="search_container">

                        <svg width="32" height="32" class="DFW_E nT46U VETef" viewBox="0 0 24 24" version="1.1"
                            aria-hidden="false">
                            <desc lang="en-US">A magnifying glass</desc>
                            <path
                                d="M16.5 15c.9-1.2 1.5-2.8 1.5-4.5C18 6.4 14.6 3 10.5 3S3 6.4 3 10.5 6.4 18 10.5 18c1.7 0 3.2-.5 4.5-1.5l4.6 4.5 1.4-1.5-4.5-4.5zm-6 1c-3 0-5.5-2.5-5.5-5.5S7.5 5 10.5 5 16 7.5 16 10.5 13.5 16 10.5 16z">
                            </path>
                        </svg>

                        <input class="search" type="search" name="search" value="{{term}}" placeholder="search profiles">
                    </div>
                </form>
            </div>
            <div class="navbar_right__cta">
                <a style="font-size: 0.9rem;" href="{% url 'news:index' %}">Home</a>
                <a class="create_news_btn" href="{% url 'news:create' %}">Create News</a>
                {% if request.user.is_authenticated %}
                <div class="profile_img_container">
                    <button id="profile_btn" role="button" tabindex="0" aria-haspopup="true" aria-expanded="true"
                        type="button" class="profile_img_btn">
                        <div class="profile_img_btn__cta1">
                            <div class="profile_img_btn__cta2">
                                <img class="profile_img" loading="lazy" role="presentation"
                                    src="{{request.user.profile.image.url}}" alt="user profile image">
                            </div>
                        </div>
                    </button>
                </div>
                <div id="logout_menu" role="menu" tabindex="-1" style="display: none;">
                    <div class="menu-popup">
                        <div class="menu-popup__popover">
                            <div class="top_arrow">
                                <div class="top_arrow__cta1"></div>
                                <div classs="top_arrow__cta2"></div>
                            </div>
                            <div class="popup_content">
                                <ul class="menu_content">
                                    <li class="menu_item">
                                        <a role="link" tabindex="-1" aria-disabled="false" class="logout__cta"
                                            href="{% url 'users:logout' %}">Logout @{{request.user.username}}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <button class="login_btn"><a href="{% url 'users:login' %}">Log in</a></button>
                {% endif %}
            </div>
        </div>
        <ul class="categories_section">
            <li><a href="{% url 'news:index' %}">Featured</a></li>
            <li><a href="{% url 'news:community' %}">Community</a></li>
            <li class="active"><a href="{% url 'users:all' %}">Profiles</a></li>
        </ul>
    </nav>

    <main class="container">
        <div class="breadcrumb">
            <small>
                <a href="{% url 'news:index' %}">Home</a>
                <span> > </span>
                <span><a href="{% url 'users:all' %}">Profiles</a></span>
            </small>
        </div>
        <div class="profiles_section">
            <div class="section_header">
                <h1 style="font-size: 2.7rem;">{{total_results}} results found for '{{term}}'</h1>
            </div>
            <div class="profile_body">
                {% for user in users %}
                    <div class="profile_card">
                        <div class="profile_image">
                            <img src="{{user.profile.image.url}}" alt="{{user.username}} profile">
                        </div>
                        <div class="profile_content">
                            <div class="username_section">
                                @{{user.username}}
                            </div>
                            <small class="fullname_section">
                                {{user.first_name}} {{user.last_name}}
                            </small>
                            <div class="total_news">
                                <span>{{user.news.count}}</span> news posted
                            </div>
                        </div>
                        {% if request.user.is_authenticated %}
                        <div class="goto_profile">
                            <a class="read_more" style="color: #fff;" href="{% url 'users:profile' username=user.username  %}">See Profile</a>
                        </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>


    <script src="{% static 'news/js/navbar.js'%}" defer></script>

</body>
</html>